server:
  port: 8888
  servlet:
    #    # 项目contextPath
    context-path: /mongodb

spring:
  application:
    name: mongodb

  data:
    mongodb:
      #不带密码
      #uri: mongodb://localhost:27017
      #账号+密码+数据库
      uri: mongodb://username:password@localhost:27017/database





#设置静态资源路径，多个以逗号分隔
spring.resources.static-locations: classpath:static/,file:static/

# 日志配置
logging:
  level:
    czs: debug
    org.springframework: WARN
    org.spring.springboot.dao: debug
    #mongodb日志
    org.springframework.data.mongodb.core: DEBUG
